# =============================================================================
# anticloud — Multi-stage Dockerfile
#
# Runtime  : Bun (oven/bun)
# Framework: Next.js 16 (output: "standalone")
# ORM      : Prisma 7 (prisma-client-js + @prisma/adapter-pg)
# Target   : Linux x86-64 (Ubuntu Server 24.04 LTS / Docker Engine)
#
# This file builds TWO images from a shared build pipeline:
#   - target `runner` -> the Next.js web server (minimal, standalone)
#   - target `worker` -> the background job consumer (worker.ts, full deps)
#
# The web app and the worker share the same source and lockfile but run as
# separate containers (see docker-compose.yml). The worker drains the Redis
# job queue (file compression + bulk-archive ZIP builds); without it those
# features enqueue jobs that are never processed.
#
# Build:
#   docker compose --env-file .env up -d --build
#
# Notes:
#   - This app has NO NEXT_PUBLIC_* variables, so nothing needs to be baked at
#     build time — every secret is injected at RUNTIME via env_file (.env).
#     The build only uses harmless placeholder values so that `next build` can
#     statically evaluate lib/env.ts, which validates env at import time.
#   - Alpine images use apk (HTTPS by default), avoiding corporate-proxy issues
#     with deb.debian.org on restricted networks.
# =============================================================================

# -----------------------------------------------------------------------------
# Base image — Alpine-based Bun for minimal size.
# Prisma ships linux-x64-musl prebuilt binaries, so musl libc (Alpine) works.
# -----------------------------------------------------------------------------
FROM oven/bun:alpine AS base
WORKDIR /app

# -----------------------------------------------------------------------------
# 1. Dependencies — install with lockfile for reproducibility.
#    Native modules need build tooling (python3, make, g++).
# -----------------------------------------------------------------------------
FROM base AS deps

RUN apk add --no-cache python3 make g++ pkgconf openssl

COPY package.json bun.lock ./
# NOTE: not using --frozen-lockfile because the committed bun.lock may drift
# from package.json (or was generated by a different bun version than the
# image). To restore reproducible frozen installs: run `bun install` locally,
# commit the refreshed bun.lock, then change this to `bun install --frozen-lockfile`.
RUN bun install

# -----------------------------------------------------------------------------
# 2. Builder — generate the Prisma client and build the standalone bundle.
# -----------------------------------------------------------------------------
FROM base AS builder
WORKDIR /app

COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Placeholder env so module-level validation (lib/env.ts) passes during
# `next build`. These values are NEVER used at runtime — the env_file (.env)
# overrides them when the container actually runs.
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV DATABASE_URL="postgresql://build:build@localhost:5432/build"
ENV REDIS_URL="redis://localhost:6379"
ENV BETTER_AUTH_SECRET="build_placeholder_secret_at_least_32_chars_long"
ENV BETTER_AUTH_URL="http://localhost:3000"
ENV APP_URL="http://localhost:3000"
ENV CRON_SECRET="build-cron-secret"
ENV MINIO_ENDPOINT="localhost"
ENV MINIO_PORT="9000"
ENV MINIO_USE_SSL="false"
ENV MINIO_ACCESS_KEY="build"
ENV MINIO_SECRET_KEY="build"
ENV MINIO_BUCKET="build"

# Prisma client into node_modules/.prisma + node_modules/@prisma/client.
RUN bunx prisma generate

# Build Next.js in standalone mode (-> .next/standalone + .next/static).
RUN bun run build

# -----------------------------------------------------------------------------
# 3. Runner — minimal production image for the Next.js web server.
#
# Alpine BusyBox includes wget (used by the healthcheck). openssl +
# ca-certificates are installed for TLS connections to Postgres/MinIO/Redis.
# -----------------------------------------------------------------------------
FROM oven/bun:alpine AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
# Internal app port. nginx terminates TLS and proxies to this port over the
# private docker network; this port is NOT published to the host.
ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

RUN apk add --no-cache openssl ca-certificates

# Non-root user (best practice for production Linux).
RUN addgroup --system --gid 1001 nextjs && \
    adduser --system --uid 1001 --ingroup nextjs nextjs

# --- Next.js standalone runtime artifacts ---------------------------------
COPY --from=builder /app/public ./public
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static

# --- Prisma CLI + schema for `prisma migrate deploy` at container startup ---
COPY --from=builder /app/prisma ./prisma
COPY --from=builder /app/prisma.config.ts ./prisma.config.ts
COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/node_modules/prisma ./node_modules/prisma
COPY --from=builder /app/node_modules/@prisma ./node_modules/@prisma
COPY --from=builder /app/node_modules/.prisma ./node_modules/.prisma
COPY --from=builder /app/node_modules/.bin/prisma ./node_modules/.bin/prisma
COPY --from=builder /app/node_modules/dotenv ./node_modules/dotenv

USER nextjs

EXPOSE 3000

CMD ["bun", "run", "server.js"]

# -----------------------------------------------------------------------------
# 4. Worker — background job consumer (worker.ts).
#
# Unlike the web server it is NOT a Next.js build artifact, so it needs the full
# dependency tree and source. It reuses the builder's node_modules (which
# already contains the generated Prisma client) plus the repo source.
# -----------------------------------------------------------------------------
FROM oven/bun:alpine AS worker
WORKDIR /app

ENV NODE_ENV=production

RUN apk add --no-cache openssl ca-certificates

RUN addgroup --system --gid 1001 nodejs && \
    adduser --system --uid 1001 --ingroup nodejs nodejs

# Full dependency tree (with generated Prisma client) + application source.
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/worker.ts ./worker.ts
COPY --from=builder /app/lib ./lib
COPY --from=builder /app/prisma ./prisma
COPY --from=builder /app/prisma.config.ts ./prisma.config.ts
COPY --from=builder /app/scripts ./scripts
COPY --from=builder /app/tsconfig.json ./tsconfig.json
COPY --from=builder /app/package.json ./package.json

RUN chown -R nodejs:nodejs /app
USER nodejs

CMD ["bun", "run", "worker.ts"]
